Add support for workflow code cells
SainsburyWellcomeCentre/aeon_docs pull request #80
Opened 2024-11-20 16:36 UTC by glopesdev

This PR introduces a custom Sphinx extension and a new JS module for the generated website to enable rendering workflow containers. The script mimics the main features of the DocFX version, but reuses heavily the [sphinx-copybutton](https://github.com/executablebooks/sphinx-copybutton) extension.

Specifically, the markdown syntax for inserting a workflow code cell is identical to the DocFX version:

```markdown
:::workflow
![Workflow](workflows/workflow.bonsai)
:::
```

The extension expects an SVG file with the same name to be located next to the workflow, e.g. the image for the workflow above is expected at `workflows/workflow.svg`.

> [!NOTE]
> Due to quirks with JS working with local files, the `fetch` function to read contents only works if the website is being hosted from a webserver (i.e. not when opening HTML directly from files). This only affects the copy action and not the image rendering so I left it for now. Workaround is to preview the website by calling the built-in python webserver `python -m http.server` from the generated `docs/html` folder.

Fixes #68

2024-11-29 17:52 UTC, lochhh requested changes
Thanks @glopesdev, cool stuff! I tried this out both locally and on [my fork](https://lochhh.github.io/aeon_docs/reference/api.html#target-api-reference) by  [copying](https://github.com/SainsburyWellcomeCentre/aeon_docs/commit/f1014508f56281ec2dc64616bced59153a649c07) the example in [Bonsai.Sleap.PredictCentroids](https://bonsai-rx.org/sleap/api/Bonsai.Sleap.PredictCentroids.html), but the URL seems to be broken. I made a suggestion to use relative URLs instead.

2024-11-29 17:52 UTC, lochhh commented on src/_static/js/workflow.js
> +        const workflowPath = img.src.replace("$", "_static/");
I tried this out and `img.src` seems to be a full URL looking like:
http://127.0.0.1:3002/docs/html/reference/reference/$workflows/CentroidModel.bonsai
so only replacing `"$"` will not give us the correct URL.

Wdyt about replacing everything up to `$` with relative URL:
```suggestion
        const workflowPath = img.src.replace(/^.*\$/, "../_static/");
```

2024-12-18 14:01 UTC, glopesdev commented
@lochhh I have rewritten the approach to use a custom extension for consistency with the image handling pipeline. Relative and deep paths should not be affected anymore, can you give your example another try?

2024-12-20 15:37 UTC, lochhh commented
> @lochhh I have rewritten the approach to use a custom extension for consistency with the image handling pipeline. Relative and deep paths should not be affected anymore, can you give your example another try?
> 
> P.S.: no need for the `$` character anymore, just a normal image link is sufficient, I have updated the PR description.

Thanks @glopesdev this is a great idea and works well with .md. I'm not sure how it works with .rst files though. In my mind I would like to have for

.rst files:
``` rst
.. workflow:: ../../workflows/CentroidModel.bonsai
   :alt: PredictCentroids
```
and .md files:
```markdown
:::{workflow} ../../workflows/CentroidModel.bonsai
   :alt: PredictCentroids
:::
```
Here is my [attempt](https://lochhh.github.io/aeon_docs/reference/sample_workflow.html) at adapting your WorkflowImageConverter for a custom WorkflowDirective (https://github.com/SainsburyWellcomeCentre/aeon_docs/commit/2bbc53b014a6e105ae23dc0ae1e138e033ccd81c).

2024-12-20 18:29 UTC, glopesdev commented
@lochhh I understand the idea but are we going to have people write documentation directly in rst syntax?

I would actually actively discourage this, since rst is only a standard in python, whereas markdown is basically everywhere.

The syntax proposed in this PR is identical between docfx markdown and sphinx markdown, so I feel it might be best to unify how we document bonsai code blocks between docfx and sphinx than to force md to be compatible with rst.

2024-12-20 20:18 UTC, glopesdev commented
@lochhh actually it looks like admonitions in MyST now support colon fences without curly brackets (https://github.com/executablebooks/MyST-Parser/issues/271) which seem to be common across markdig, pandoc and now myst.

2025-01-02 16:50 UTC, lochhh commented
> @lochhh I understand the idea but are we going to have people write documentation directly in rst syntax?
> 
> I would actually actively discourage this, since rst is only a standard in python, whereas markdown is more accessible.
> 
> The syntax proposed in this PR is identical between docfx markdown and sphinx markdown, so I feel it might be best to unify how we document bonsai code blocks between docfx and sphinx than to force md to be compatible with rst.
> 

Thanks again @glopesdev. I totally agree with your point of having a consistent markdown syntax between docfx and sphinx. From what I understand, the current approach is that we place an "image" in a custom "workflow" container and manipulate this image via the WorkflowImageConverter, and then workflow.js finds the matching container and adds the copy button. What I'm unsure about is implementing this as an ImageConverter, as something like the below (i.e. without the `workflow` container) would still render the image, only without the copy button:
```markdown
![PredictCentroids](../workflows/CentroidModel.bonsai)
```

My suggestion for a directive is to have something similar to embedding mermaid diagrams: instead of providing mermaid file/code, we provide the workflow file, and the image would be rendered. I learnt from [sphinx's mermaid extension](https://github.com/mgaitan/sphinxcontrib-mermaid/tree/master) that setting `myst_fence_as_directive = ["workflow"]` would allow us to use the `workflow` directive as a markdown code block (see [updated preview](https://lochhh.github.io/aeon_docs/reference/sample_workflow.html)):
````markdown
```workflow
../workflows/CentroidModel.bonsai
```
````
This syntax is also similar to that for [docfx's mermaid diagram](https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#mermaid-diagrams). With a directive, we also get a similar RST syntax "for free" (even if we don't need it).
That said, I'm aware that much more work has been done on the bonsai docfx side than here - it is easier to directly adopt the current way of documenting bonsai code blocks, than reinventing the wheel - was fun to try it out anyway 😁 

> @lochhh actually it looks like admonitions in MyST now support colon fences without curly brackets ([executablebooks/MyST-Parser#271](https://github.com/executablebooks/MyST-Parser/issues/271)) which seem to be common across markdig, pandoc and now myst.

The [closing comment](https://github.com/executablebooks/MyST-Parser/issues/271#issuecomment-747535902) suggests the curly braces are necessary to [distinguish between highlighting languages (\```python) and directives(\```{python})](https://github.com/executablebooks/MyST-Parser/issues/185#issuecomment-659339708).

> Ultimately all MyST code must have an equivalent in rST. Do you know what would be the .rst equivalent of the current .md syntax?

The rst equivalent for the current custom container syntax would be: 
```rst
.. container:: workflow

    .. raw:: html

        <p>

    .. image:: ../workflows/CentroidModel.bonsai
        :alt: Alternative text

    .. raw:: html

        </p>
```
(☝️ This definitely gives us another reason to discourage documenting bonsai workflows in rst.) 
as opposed to the directive approach:
```rst
.. workflow::
    :alt: Alternative text
    
    ../workflows/CentroidModel.bonsai
```
to get to:
```html
<div class="workflow docutils container">
   <p>
      <img alt="Alternative text" src="../_images/CentroidModel.svg">
   </p>
</div>
```

2025-01-08 11:16 UTC, glopesdev commented
> My suggestion for a directive is to have something similar to embedding mermaid diagrams: instead of providing mermaid file/code, we provide the workflow file, and the image would be rendered

@lochhh As a last defense of the image converter approach, I guess I was originally seeing this problem as a conversion between the `.bonsai` file format and SVG files. Currently it is down by assuming the exported file is right there, but actually in current bonsai doc sites we export the SVG files directly from source code, so in the future this could literally be a conversion process where we take the workflow file and output the SVG without checking it into version control.

2025-01-08 11:20 UTC, glopesdev commented
> The rst equivalent for the current custom container syntax would be:

I actually have a question about the rst syntax. Have you tried whether the following would work?

```rst
.. container:: workflow
    .. image:: ../workflows/CentroidModel.bonsai
        :alt: Alternative text
```

2025-01-08 16:58 UTC, lochhh commented on src/_static/js/workflow.js
> +        imgParent.remove();
> > The rst equivalent for the current custom container syntax would be:
> 
> I actually have a question about the rst syntax. Have you tried whether the following would work?
> 
> ```
> .. container:: workflow
>
>     .. image:: ../workflows/CentroidModel.bonsai
>         :alt: Alternative text
> ```

Actually, the above would work if we change this line as follows:

```suggestion
        // remove the parent p element, if it exists
        if (imgParent.nodeName.toLowerCase() === "p") {
            imgParent.remove();
        }
```
Because in .md the custom container places the `<img>` within `<p>`, i.e. `<div><p><img>...</img></p></div>`, whereas in .rst we'd get `<div><img>...</img></div>`, and removing the parent element of the img means we remove the entire `<div>`.

2025-01-08 17:08 UTC, lochhh commented on src/_static/js/workflow.js
> +        imgParent.remove();
Happy to merge this PR once the above is resolved, and perhaps revisit the syntax discussion later. Nonetheless, it's nice to know the reasoning behind the chosen syntax, as I thought of it more as "code that one can copy", than a special kind of image that needs to be converted.

2025-01-17 09:44 UTC, lochhh commented on src/_static/js/workflow.js
> +        imgParent.remove();
@glopesdev in case you missed this 😄

2025-02-02 15:43 UTC, lochhh approved these changes
🚀

2025-02-02 16:18 UTC, merged